First try to manage PLATFORM GCC
Brewskey/spark-protocol pull request #108
Opened 2017-06-13 16:38 UTC by straccio

Now the GCC platform can connect correctly to the cloud

2017-06-13 16:43 UTC, jlkalberer reviewed
Can you explain what these checks are actually doing?

2017-06-13 16:43 UTC, jlkalberer commented on src/lib/FirmwareManager.js
> +    if(platformID==3){
nit: `platformID === 3`

2017-06-13 16:43 UTC, jlkalberer commented on src/server/DeviceServer.js
> +        )[0];
This doesn't seem correct. `find` should return  a single module.

2017-06-13 19:57 UTC, straccio commented on src/lib/FirmwareManager.js
> +    if(platformID==3){
GCC have platform id = 3.
GCC doesn't have app module ad the app_hash

2017-06-13 20:14 UTC, straccio commented on src/server/DeviceServer.js
> +        )[0];
at this moment i can't try it with one real Photon.
`const {uuid} uuid = FirmwareManager.getAppModule(
          description.systemInformation,
);` 
is egual to       
`uuid = FirmwareManager.getAppModule(
          description.systemInformation,
)[0];`
I'm wrong?

2017-06-13 20:59 UTC, jlkalberer commented on src/server/DeviceServer.js
> +        )[0];
Yeah -- `FirmwareManager.getAppModule` uses `find` which will return a single module.

The module returns `{uuid: string, .....otherStuff}`

when you do `const {uuid} = FirmWareManager.getAppModule` it uses destructuring so you only get the `uuid` prop out of the returned object.

I think the `platformID` check (above) will be fine but we probably don't need this change.

2017-06-16 05:14 UTC, straccio commented on src/server/DeviceServer.js
> +        )[0];
Without GCC platform can't connect because FirmwareManager.getAppModule throw a null exception

2017-06-16 14:47 UTC, jlkalberer requested changes

2017-06-16 14:47 UTC, jlkalberer commented on src/server/DeviceServer.js
> +        )[0];
I know -- the code you added before is fine. The code you commented out should be here -- not the way you are using `getAppModule` now. It doesn't return an array and the code we had before was correct.  You can keep the old code in a try/catch to handle GCC.

2017-06-16 14:47 UTC, jlkalberer commented on src/server/DeviceServer.js
> +      let uuid;
This definition should be closer to where it's set.
I think it should also be initialized to `null`

2017-06-16 14:47 UTC, jlkalberer commented on src/server/DeviceServer.js
> +      } catch (uuidErr) {
nit: `} catch (ignore) {`

2017-07-07 01:30 UTC, jlkalberer requested changes

2017-07-07 01:30 UTC, jlkalberer commented on src/lib/FirmwareManager.js
> +    // if(platformID === 3){
Remove this. We don't allow commented code

2017-07-07 01:30 UTC, jlkalberer commented on src/server/DeviceServer.js
> +  // _onDeviceReady = async (device: Device): Promise<void> => {
???? What

2017-07-07 13:44 UTC, jlkalberer approved these changes
This looks ok.

You only changed the code in two places right? The rest was from prettier?

2017-09-05 21:28 UTC, jlkalberer requested changes
I'm not sure why you're touching all these files when it's mostly a 3 line addition.  Is this `prettier` doing its thing?

Also, please remove all the merge conflicts. This should not be merged into master.

2017-09-05 21:28 UTC, jlkalberer commented on package.json
> +  "main": "./src/index.js",
nit: revert

2017-09-05 21:28 UTC, jlkalberer commented on src/defaultBindings.js
> +  //   container.bindClass('DeviceKeyRepository', DeviceKeyFileRepository, [
Remove this

2017-09-05 21:28 UTC, jlkalberer commented on src/defaultBindings.js
> +  // >>>>>>> upstream/dev
remove

2017-09-05 21:28 UTC, jlkalberer commented on src/defaultBindings.js
> +    //     'DeviceKeyRepository',
Remove

2017-09-05 21:28 UTC, jlkalberer commented on src/defaultBindings.js
> +    //     'DeviceAttributeRepository',
Remove

2017-09-05 21:28 UTC, jlkalberer commented on src/server/DeviceServer.js
> +          //           const appModule = FirmwareManager.getAppModule(systemInformation);
Remove

2017-09-06 14:34 UTC, jlkalberer approved these changes

2017-09-06 14:34 UTC, merged