publisher/ deviceServer
Brewskey/spark-protocol pull request #11
Opened 2016-12-29 20:33 UTC by AntonPuko

2016-12-29 20:36 UTC, AntonPuko commented on src/clients/SparkCore.js
> -  _connectionKey: ?string = null;
connectionKey is redundant..its used only in some console.logs inside sparkCore and in DeviceServer for checking if the device is in devicesByIdMap...

2016-12-29 20:37 UTC, AntonPuko commented on src/lib/EventPublisher.js
> +  unsubscribeBySubscriberID = (subscriberID: string): void => {
add subscriberID to be able to clean all listeners for the current device if it is disconnected.

2016-12-29 20:41 UTC, AntonPuko commented on src/server/DeviceServer_v2.js
> +    // uri -> /e/?u    --> firehose for all my devices
this info is very messy..I understand nothing from it, do I need to remove?

2016-12-29 20:43 UTC, AntonPuko commented on src/server/DeviceServer_v2.js
> +    const fromMyDevicesOnly = query && !!query.match('u');
not sure about name of this var. what is this for. it checks if device wants to listen event from devices with the same ownerID as it has. `Particle.subscribe( lall, lulu, MY_DEVICES) ` - in firmware

2016-12-29 20:58 UTC, AntonPuko commented on src/lib/EventPublisher.js
> +      .forEach((subscription) => {
native js Map() doesn't have filter()..didn't now that before.

2016-12-29 22:07 UTC, jlkalberer requested changes

2016-12-29 22:07 UTC, jlkalberer commented on src/clients/SparkCore.js
> -  _connectionKey: ?string = null;
Yeah, it is convenient for the logs though... Maybe just have a global counter and use that instead.

2016-12-29 22:07 UTC, jlkalberer commented on src/clients/SparkCore.js
> -        cache_key: this._connectionKey,
This still needs to be there. It helps me when debugging.

2016-12-29 22:07 UTC, jlkalberer commented on src/clients/SparkCore.js
> -        cache_key: this._connectionKey,
ditto

2016-12-29 22:07 UTC, jlkalberer commented on src/lib/EventPublisher.js
> +      .forEach((subscription) => {
This seems odd... Why don't you:
```
const subscription = this._subscriptionsByID.get(subscriptionID)
if (subscription) {
  this.unsubscribe(subscription.id);
}
```

2016-12-29 22:07 UTC, jlkalberer commented on src/server/DeviceServer_v2.js
> +    // uri -> /e/?u    --> firehose for all my devices
Nope, please keep it.  It's the COAP protocol

2016-12-29 22:07 UTC, jlkalberer commented on src/server/DeviceServer_v2.js
> +    const fromMyDevicesOnly = query && !!query.match('u');
`isFromMyDevices`

2016-12-30 00:13 UTC, jlkalberer approved these changes

2016-12-30 00:13 UTC, merged