Cooldown update-firmware and  flash
Brewskey/spark-protocol pull request #139
Opened 2018-07-31 07:27 UTC by haeferer

Hi, i started working again on my rabbit-based-version and found some actual problems: 

## patch for #138 

## patch for FastOTA Update fail on slow / instable networks (missing chunk algo)

Problem:
if your particle is connected to a slow network and you have a lot of app code, sometimes FASTOTA will fail.
 
Reason:
the missed_chunk algorithm is to aggressive (there is not enough time for the board to send missed chunk informations to the server, so the overall Update will fail)

Solution:
Slow down FastOTA Responses for missed chunks, to give particle time to answer

2018-07-31 09:33 UTC, jlkalberer commented
This is going to take a while to merge. @AntonPuko let's be very thorough with this review.

Also, how long does it take to flash the device with your change? Is there any way that we can try the very aggressive OTA first and then default to your delays after? (I haven't looked at the code yet FYI)

2018-07-31 12:09 UTC, haeferer commented
For my tests the flashtime is comparable . You only have to wait longer for missing_chunks info (currently i tryed 500ms every 50 chunks)

Fast OTA currently works by sending Chunks as Fast as Possible and look if missed_chunks arrives during this OTA. This works fine for normal Connections but not for 
* very fast (direct WiFi) -> Particle is not fast enough to handle
* slow connections (answer from particle tooks to Long)

2018-08-05 12:11 UTC, jlkalberer commented
Move the `.env` changes into another PR so it's easier to review. This is way too large as is.

2018-08-05 12:40 UTC, jlkalberer requested changes

2018-08-05 12:40 UTC, jlkalberer commented on src/lib/Flasher.js
> +        if (canUseFastOTA) {
Wouldn't this be a bug if it was `!canUseFastOTA`? Seems like this wouldn't work before...

2018-08-05 12:40 UTC, jlkalberer commented on src/lib/Flasher.js
> +function waitFor(ms: number): Promise {
consider:

```
const waitFor = (ms: number): Promise<void> => 
  new Promise((resolve: Promise.resolve) => setTimeout((): void => resolve(), ms));
```

2018-08-05 12:40 UTC, jlkalberer commented on src/lib/Flasher.js
> +      if (chunkCount % 50 === 0) await waitFor(500);
For Photon there is generally less than 50 chunks so this code will never be run. If it does, I think 500ms is way too long of a wait time.

I think we can have small delay here of 100ms. If this is too much for the low bandwidth scenarios, the missed chunks should handle it and add a larger delay between chunks.

2018-08-05 12:40 UTC, jlkalberer commented on src/lib/Flasher.js
> -        if (!canUseFastOTA) {
Was this a bug then?

2018-08-05 12:40 UTC, jlkalberer commented on src/lib/Flasher.js
> +        logger.info(
Have you actually built an environment to test this scenario?

I'm interested in the case where you have the low bandwidth. Let's say you have a failure at chunk 1 and a failure at chunk n-1. The time between sending the two chunks is over a half second. In that case this function would exit before it saw the second missed chunk and wouldn't send the second chunk.

---

I think I heard that Particle added a new event from the system firmware that may help with this scenario but I'm not 100% sure.

2018-08-05 12:40 UTC, jlkalberer commented on src/scripts/update-firmware-binaries.js
> +function CollectDotEnv() {
Please put this in another PR.

2018-08-05 12:41 UTC, jlkalberer commented
I'd love to try to merge all of your other changes into this branch. I'm guessing you have done a lot of work for horizontal scaling.

2019-02-10 15:53 UTC, closed without merging

2019-02-10 15:53 UTC, jlkalberer commented on src/lib/Flasher.js
> -    if (this._missedChunks.size) {
@haeferer - I think this is solved if we just remove this if-statement. We should always wait a bit for the missing chunk whether we have any or we don't.