fix socket disconnect messages
Brewskey/spark-protocol pull request #15
Opened 2017-01-02 17:51 UTC by AntonPuko

Closes: https://github.com/Brewskey/spark-server/issues/55

2017-01-02 17:52 UTC, AntonPuko commented on src/clients/Device.js
> +      (): void => this.disconnect('socket timeout'),
socket 'timeout' event doesn't have args.

2017-01-02 17:54 UTC, AntonPuko commented on src/clients/Device.js
> +      (): void => this.disconnect('socket close'),
'close' event have `had_error` : Boolean, arg. but no needs for this, because if there is an error, 'error' event will be dispatched before.

2017-01-03 03:13 UTC, jlkalberer requested changes

2017-01-03 03:13 UTC, jlkalberer commented on src/clients/Device.js
> +        logger.error(`Error cleaning up _decipherStream: ${error}`);
nit: `cipherStream`

2017-01-03 15:14 UTC, merged