add default TTL
Brewskey/spark-protocol pull request #33
Opened 2017-01-13 10:58 UTC by AntonPuko

2017-01-13 15:17 UTC, jlkalberer requested changes

2017-01-13 15:17 UTC, jlkalberer commented on dist/server/DeviceServer.js
> +                  ttl: message.getMaxAge() > 0 && message.getMaxAge(),
I don't think this is correct. You should just replace `0` with the `DEFAULT_EVENT_TTL`

2017-01-13 15:17 UTC, jlkalberer commented on src/lib/EventPublisher.js
> +const DEFAULT_EVENT_TTL = 60;
Maybe this goes in settings so it's shared everywhere.

2017-01-13 15:17 UTC, jlkalberer commented on src/server/DeviceServer.js
> +      ttl: message.getMaxAge() > 0 && message.getMaxAge(),
Same with this... We should be using the constant if it's zero.

2017-01-14 03:36 UTC, jlkalberer requested changes

2017-01-14 03:36 UTC, jlkalberer commented on src/settings.js
> -  DEVICE_DIRECTORY: path.join(__dirname, './data/deviceKeys'),
These actually need to be here.

2017-01-14 11:46 UTC, AntonPuko commented on src/settings.js
> -  DEVICE_DIRECTORY: path.join(__dirname, './data/deviceKeys'),
ops, fixed

2017-01-14 17:28 UTC, merged